# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "HelloSayer": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://amaiya.github.io/nbdev_test/"

git_url = "https://github.com/amaiya/nbdev_test/tree/master/"

def custom_doc_links(name): return None
